global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "command-service"
    metrics_path: "/api/commands/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["command-service:8080"]
    
  - job_name: "query-service"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["query-service:8081"]

  - job_name: "api-gateway"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["api-gateway:80"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "elasticsearch"
    metrics_path: "/_prometheus/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["elasticsearch:9200"]
        
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]