server:
  port: 8081
  basePath: "/api/queries"

mongodb:
  uri: "mongodb://localhost:27017"
  database: "ecommerce"
  poolSize: 100
  timeout: 30

elasticsearch:
  addresses: ["http://localhost:9200"]
  username: ""
  password: ""
  indexPrefix: "ecommerce_"

redis:
  address: "localhost:6379"
  password: ""
  db: 0
  poolSize: 10
  ttl: 3600  # 1 hour in seconds

kafka:
  brokers: ["localhost:9092"]
  groupId: "query-service"
  topics:
    product: "products"
    inventory: "inventory"
    order: "orders"

logging:
  level: "debug"  # debug, info, warn, error
  format: "json"  # json or text